/**
 * Generated by tsnapi — public API snapshot of `node-starter`
 */
// #region Functions
export declare function greet(): string;
// #endregion

// #region Variables
export declare const msg: string;
// #endregion